# Generated by Django 6.0 on 2025-12-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuar_promet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('Red', 'red'), ('Green', 'green'), ('Blue', 'blue'), ('White', 'White'), ('Black', 'black'), ('Grey', 'grey'), ('Yellow', 'yellow'), ('Brown', 'brown'), ('Beige', 'beige')], max_length=200),
        ),
    ]
