# Generated by Django 6.0 on 2026-01-14 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuar_promet', '0002_alter_product_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='depth',
            new_name='length',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='height',
            new_name='thickness',
        ),
    ]
