# Generated by Django 6.0 on 2026-01-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuar_promet', '0003_rename_depth_product_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('Kastamonu Entegre', 'Kastamonu Entegre'), ('Starwood', 'Starwood'), ('Swiss Krono', 'Swiss Krono')], default='Kastamonu Entegre', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='surface',
            field=models.CharField(blank=True, choices=[('Soft Touch', 'Soft Touch'), ('Glossy', 'Glossy')], max_length=200, null=True),
        ),
    ]
