# Generated by Django 6.0 on 2026-01-14 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuar_promet', '0004_product_brand_product_code_product_surface'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
    ]
