# Generated by Django 6.0 on 2026-01-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuar_promet', '0007_alter_product_brand_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='band_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
