# Generated by Django 6.0 on 2026-01-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuar_promet', '0008_product_band_length_product_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='thickness',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
